all:
  hosts:
    node1:
      ansible_host: 10.0.1.1
      ip: 10.0.1.1
      access_ip: 10.0.1.1
    node2:
      ansible_host: 10.0.1.2
      ip: 10.0.1.2
      access_ip: 10.0.1.2
    node3:
      ansible_host: 10.0.1.3
      ip: 10.0.1.3
      access_ip: 10.0.1.3
    node4:
      ansible_host: 10.0.1.4
      ip: 10.0.1.4
      access_ip: 10.0.1.4
    node5:
      ansible_host: 10.0.1.5
      ip: 10.0.1.5
      access_ip: 10.0.1.5
    node6:
      ansible_host: 10.0.1.6
      ip: 10.0.1.6
      access_ip: 10.0.1.6
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
